In [24]:
import json
from pathlib import Path

import pandas as pd

In [25]:
files = list(Path("../data").glob("*.json"))

print("Antal JSON-filer:", len(files))

Antal JSON-filer: 60

In [33]:
# Läser in flygdata från JSON-filer och skapar en DataFrame (df)

rows = []

for file in files:
    with file.open(encoding="utf-8") as f:
        data = json.load(f)

    direction, airport, flight_date = file.stem.split("_", 2)
    flights = data.get("flights", []) if isinstance(data, dict) else data

    for flight in flights:
        if isinstance(flight, dict):
            row = flight.copy()
            row["airport"] = airport
            row["flight_date"] = flight_date
            row["direction"] = direction
            rows.append(row)

df = pd.DataFrame(rows)

In [34]:
print(df.columns.tolist())

['flightId', 'arrivalAirportSwedish', 'arrivalAirportEnglish', 'airlineOperator', 'departureTime', 'locationAndStatus', 'checkIn', 'codeShareData', 'flightLegIdentifier', 'viaDestinations', 'remarksEnglish', 'remarksSwedish', 'diIndicator', 'airport', 'flight_date', 'direction', 'departureAirportSwedish', 'departureAirportEnglish', 'arrivalTime', 'baggage']

In [29]:
print(df.shape)

(2704, 17)

In [9]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 2704 entries, 0 to 2703
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   flightId                 2704 non-null   str
 1   arrivalAirportSwedish    1346 non-null   str
 2   arrivalAirportEnglish    1346 non-null   str
 3   airlineOperator          2704 non-null   object
 4   departureTime            1346 non-null   object
 5   locationAndStatus        2704 non-null   object
 6   checkIn                  1346 non-null   object
 7   codeShareData            2704 non-null   object
 8   flightLegIdentifier      2704 non-null   object
 9   viaDestinations          2704 non-null   object
 10  remarksEnglish           2704 non-null   object
 11  remarksSwedish           2704 non-null   object
 12  diIndicator              2704 non-null   str
 13  departureAirportSwedish  1358 non-null   str
 14  departureAirportEnglish  1358 non-null   str
 15  arrivalTime              1358 non-null   object
 16  baggage                  1358 non-null   object
dtypes: object(11), str(6)
memory usage: 359.3+ KB

,flightId,arrivalAirportSwedish,arrivalAirportEnglish,airlineOperator,departureTime,locationAndStatus,checkIn,codeShareData,flightLegIdentifier,viaDestinations,remarksEnglish,remarksSwedish,diIndicator,departureAirportSwedish,departureAirportEnglish,arrivalTime,baggage
0,OJ804,Visby,Visby,"{'iata': 'OJ', 'icao': 'NYX', 'name': 'Nyxair'}",{'scheduledUtc': '2026-10-10T10:00:00Z'},"{'terminal': 'T1', 'flightLegStatus': 'DEL', '...",{},[],"{'callsign': 'NYX804', 'flightId': 'OJ804', 'f...",[],[],[],D,NaN,NaN,NaN,NaN
1,FR4384,Zagreb,Zagreb,"{'iata': 'FR', 'icao': 'RYR', 'name': 'Ryanair...",{'scheduledUtc': '2026-10-11T15:00:00Z'},"{'terminal': 'T1', 'flightLegStatus': 'DEL', '...",{},[],"{'callsign': 'RYR4384', 'flightId': 'FR4384', ...",[],[],[],S,NaN,NaN,NaN,NaN
2,W45196,Tirana,Tirana,"{'iata': 'W4', 'icao': 'WMT', 'name': 'Wizz Ai...",{'scheduledUtc': '2026-10-11T07:10:00Z'},"{'terminal': 'T1', 'flightLegStatus': 'DEL', '...",{},[],"{'callsign': 'WMT5196', 'flightId': 'W45196', ...",[],[],[],I,NaN,NaN,NaN,NaN
3,W61220,Cluj Napoca,Cluj Napoca,"{'iata': 'W6', 'icao': 'WZZ', 'name': 'Wizz Air'}",{'scheduledUtc': '2026-10-11T14:45:00Z'},"{'terminal': 'T1', 'flightLegStatus': 'DEL', '...",{},[],"{'callsign': 'WZZ1220', 'flightId': 'W61220', ...",[],[],[],S,NaN,NaN,NaN,NaN
4,DK1466,Rhodos,Rhodes,"{'iata': 'DK', 'icao': 'VKG', 'name': 'Sunclas...",{'scheduledUtc': '2026-10-11T05:00:00Z'},"{'terminal': 'T1', 'flightLegStatus': 'DEL', '...",{},[],"{'callsign': 'VKG1466', 'flightId': 'DK1466', ...",[],[],[],S,NaN,NaN,NaN,NaN

In [11]:
df["airlineOperator"].value_counts().head(10)

airlineOperator
{'iata': 'SK', 'icao': 'SAS', 'name': 'SAS Scandinavian Airlines'}    948
{'iata': 'D8', 'icao': 'NSZ', 'name': 'Norwegian'}                    346
{'iata': 'FR', 'icao': 'RYR', 'name': 'Ryanair Ltd'}                  310
{'iata': 'AY', 'icao': 'FIN', 'name': 'Finnair'}                      103
{'iata': 'LH', 'icao': 'DLH', 'name': 'Lufthansa'}                     90
{'iata': 'W6', 'icao': 'WZZ', 'name': 'Wizz Air'}                      68
{'iata': 'KL', 'icao': 'KLM', 'name': 'KLM'}                           64
{'iata': 'EW', 'icao': 'EWG', 'name': 'Eurowings'}                     58
{'iata': 'OJ', 'icao': 'NYX', 'name': 'Nyxair'}                        50
{'iata': 'FT', 'icao': 'FT', 'name': 'FROST Air'}                      39
Name: count, dtype: int64

In [14]:
# Kontrollerar antalet saknade värden i varje kolumn
df.isna().sum()

flightId                      0
arrivalAirportSwedish      1358
arrivalAirportEnglish      1358
airlineOperator               0
departureTime              1358
locationAndStatus             0
checkIn                    1358
codeShareData                 0
flightLegIdentifier           0
viaDestinations               0
remarksEnglish                0
remarksSwedish                0
diIndicator                   0
departureAirportSwedish    1346
departureAirportEnglish    1346
arrivalTime                1346
baggage                    1346
dtype: int64

In [35]:
#Antal flyg på varje flygplats, uppdelat på ankomster och avgångar.
df.groupby(["airport", "direction"]).size().unstack()

direction  arrivals  departures
airport
ARN             944         937
BMA              30          30
GOT             214         211
KRN               5           5
LLA              42          40
MMX              47          47
OSD              11          11
RNB               7           7
UME              30          30
VBY              28          28